- name: Setup Bastion Host
  hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Import Bastion variables
      include_vars: vars/bastion_setup.txt

    - name: Import VPC variables
      include_vars: vars/id-vars.txt

    - name: Create Bastion key 
      amazon.aws.ec2_key:
        name: bastion_key 
        region: '{{ region }}'
      register: keyout

    - name: Save Bastion Private Key
      copy:
        content: '{{ keyout.key.private_key }}'
        dest: './keys/bastion_key.pem'
      when: keyout.changed

    - name: Create Bastion Security group 
      amazon.aws.ec2_security_group:
        name: "bastion_sg"
        description: security group for bastion host
        vpc_id: '{{ vpcID }}'
        region: '{{ region }}'
        rules:
          - proto: tcp
            ports:
              - 22
            cidr_ip: '{{ MYIP }}'
            rule_desc: allow ssh only from my IP
      register: bastion_sg_out

    - name: Create Bastion instance
      amazon.aws.ec2_instance:
        key_name: '{{ keyout.key.name}}'
        region: '{{ region }}'
        vpc_subnet_id: '{{ pubSub2ID }}'
        instance_type: t2.micro
        security_group: '{{ bastion_sg_out.group_id }}'
        network_interfaces:
          - assign_public_ip: true
        image_id: '{{ bastion_ami }}'
        wait: yes
        instance_tags: 
          Name: "Bastion Host"
          Project: vpro
          Owner: Rajat Rulaniya
        exact_count: 1
        count_tag:
          Name: "Bastion Host"
          Project: vpro
          Owner: Rajat Rulaniya

      register: bastionHost_out 