- hosts: localhost
  connection: local 
  gather_facts: False

  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_setup.txt

    - name: Create Vprofile VPC
      amazon.aws.ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Create Public Subnet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PubSub1Cidr }}'
        az: '{{ zone1 }}'
        region: "{{ region }}"
        map_public: true
        resource_tags:
          Name: vpro-PublicSub1
      register: pubSub1out
        

    - name: Create Public Subnet 2 in Zone 2
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PubSub2Cidr }}'
        az: '{{ zone2 }}'
        region: "{{ region }}"
        map_public: true
        resource_tags:
          Name: vpro-PublicSub2
      register: pubSub2out

    - name: Create Public Subnet 3 in Zone 3
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PubSub3Cidr }}'
        az: '{{ zone3 }}'
        region: "{{ region }}"
        map_public: true
        resource_tags:
          Name: vpro-PublicSub3
      register: pubSub3out

    - name: Create Private Subnet 1 in Zone 1
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PrivSub1Cidr }}'
        az: '{{ zone1 }}'
        region: "{{ region }}"
        resource_tags:
          Name: vpro-PrivateSub1
      register: privSub1out
        
    - name: Create Private Subnet 2 in Zone 2
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PrivSub2Cidr }}'
        az: '{{ zone2 }}'
        region: "{{ region }}"
        resource_tags:
          Name: vpro-PrivateSub2
      register: privSub2out
    
    - name: Create Private Subnet 3 in Zone 3
      amazon.aws.ec2_vpc_subnet:
        state: "{{ state }}"
        vpc_id: '{{ vpcout.vpc.id }}'
        cidr: '{{ PrivSub3Cidr }}'
        az: '{{ zone3 }}'
        region: "{{ region }}"
        resource_tags:
          Name: vpro-PrivateSub3
      register: privSub3out

    
    - name: Create Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: '{{ vpcout.vpc.id }}'
        state: '{{ state }}'
        region: '{{ region }}'
        resource_tags:
          Name: vpro-IGateWay
      register: igw

    - name: Create Public Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: '{{ vpcout.vpc.id }}'
        state: '{{ state }}'
        region: '{{ region }}'

        resource_tags:
          Name: Public-RT

        subnets:
          - '{{ pubSub1out.subnet.id }}'
          - '{{ pubSub2out.subnet.id }}'
          - '{{ pubSub3out.subnet.id }}'

        routes:
          - dest: 0.0.0.0/0
            gateway_id: '{{ igw.gateway_id }}'
          - dest: ::/0
            gateway_id: '{{ igw.gateway_id }}'
      register: public_route_table

    - name: Create NAT Gateway in Public Subnet 1
      amazon.aws.ec2_vpc_nat_gateway:
        state: '{{ state }}'
        region: '{{ region }}'
        subnet_id: '{{ pubSub1out.subnet.id }}'
        if_exists_do_not_create: true
        resource_tags:
          Name: NAT-gw-pubSub1
      register: nat_gw_pubSub1


    - name: Create Private Route Table
      amazon.aws.ec2_vpc_route_table:
        vpc_id: '{{ vpcout.vpc.id }}'
        state: '{{ state }}'
        region: '{{ region }}'

        resource_tags:
          Name: Private-RT

        subnets:
          - '{{ privSub1out.subnet.id }}'
          - '{{ privSub2out.subnet.id }}'
          - '{{ privSub3out.subnet.id }}'
        
        routes:
          - dest: '{{ vpcCidr }}'
            gateway_id: 'local'
          - dest: '0.0.0.0/0'
            gateway_id: '{{ nat_gw_pubSub1.nat_gateway_id }}'

      register: private_route_table

