---
- name: Deploy SQL file on Db server 
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Copy SQL to dbsrv
      copy:
        src: files/db_backup.sql
        dest: /tmp/db_backup.sql

    - name: Restoring DB
      mysql_db:
        name: accounts
        login_user: '{{ lookup("env", "dbuser") }}'
        login_password: '{{ lookup("env", "dbpass") }}'
        state: import
        target: /tmp/db_backup.sql
    
      notify:
        - Restart mysql

  handlers:
    - name: Restart mysql
      service:
        name: mysql
        state: restarted