---
- name: Setup RabbitMQ
  hosts: rmqsrvgrp
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      loop:
        - curl
        - gnupg
        - apt-transport-https

    - name: Add RabbitMQ & Erlang GPG keys
      apt_key: 
        url: '{{ item }}'
        state: present
      loop:
        - "https://keys.openpgp.org/vks/v1/by-fingerprint/0A9AF2115F4687BD29803A206B73A36E6026DFCA"
        - "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-erlang.E495BB49CC4BBE5B.key"
        - "https://github.com/rabbitmq/signing-keys/releases/download/3.0/cloudsmith.rabbitmq-server.9F4587F226208342.key"

    - name: Add RabbitMQ repositories
      apt_repository:
        repo: '{{ item }}'
        state: present

      loop:
        - "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main"
        - "deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main"
        - "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main"
        - "deb-src [signed-by=/usr/share/keyrings/rabbitmq.E495BB49CC4BBE5B.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-erlang/deb/ubuntu noble main"
        - "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main"
        - "deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa1.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main"
        - "deb [arch=amd64 signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main"
        - "deb-src [signed-by=/usr/share/keyrings/rabbitmq.9F4587F226208342.gpg] https://ppa2.rabbitmq.com/rabbitmq/rabbitmq-server/deb/ubuntu noble main"

    - name: Install Erlang & RabbitMQ
      apt:
        name: '{{ item }}'
        state: present
        update_cache: yes
      
      loop:
        - erlang-base
        - erlang-asn1
        - erlang-crypto
        - erlang-eldap
        - erlang-ftp
        - erlang-inets
        - erlang-mnesia
        - erlang-os-mon
        - erlang-parsetools
        - erlang-public-key
        - erlang-runtime-tools
        - erlang-snmp
        - erlang-ssl
        - erlang-syntax-tools
        - erlang-tftp
        - erlang-tools
        - erlang-xmerl
        - rabbitmq-server

    - name: Enable & Start RabbitMQ server
      service: 
        name: rabbitmq-server
        state: started 
        enabled: yes

    - name: Config Setup
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config

    - rabbitmq_user: 
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present

    - name: Enables rabbitmq_management plugin
      rabbitmq_plugin:
        name: rabbitmq_management
        state: enabled 
      
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted 
