---
- name: Build Artifact ROOT.war & SQL file to be copied in files/ folder
  import_playbook: build.yml

- name: Set Hosts to IP mapping in /etc/hosts/ file of all servers
  import_playbook: set_host_ip_map.yml

- name: Setup dbserver
  import_playbook: db.yml

- name: Deploy SQL file on Db server 
  import_playbook: dbdeploy.yml

- name: Setup Memcached
  import_playbook: memcache.yml

# - name: Setup RabbitMQ
#   import_playbook: rabbitmq.yml

- name: Setup Tomcat Application server
  import_playbook: appserver.yml

- name: Setup Nginx webserver
  import_playbook: web.yml
